name: dart_orm_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
repository: https://github.com/andyhorn/dart_orm_generator

environment:
  sdk: ^3.2.2

# Add regular dependencies here.
dependencies:
  analyzer: ^6.4.0
  basic_utils: ^5.7.0
  code_builder: ^4.10.0
  dart_style: ^2.3.4
  postgres: ^3.0.6
  source_gen: ^1.5.0
  build: ^2.4.1
  dart_orm_annotation:
    path: ../dart_orm_annotation

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  build_runner: ^2.4.8
